# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "http://icra-2019-uwroboticsperception.ge.issia.cnr.it/"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: Underwater Robotics Perception Workshop - ICRA 2019
# Short description of your site
description: Full-day Workshop
bigimg: ["/img/uw_bg_1.jpg","/img/CADDY_bts_cetvrtak_138.jpg","/img/pladypus.jpg","/img/gazebo_dexrov.png","/img/rov_dexrov.jpg","/img/sonar_caddy.png"]

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Overview: "http://icra-2019-uwroboticsperception.ge.issia.cnr.it/2019-01-12-overview/"
  #Speakers: "http://icra-2019-uwroboticsperception.ge.issia.cnr.it/2019-01-10-speakers/"
  Program:
    - Speakers: "http://icra-2019-uwroboticsperception.ge.issia.cnr.it/2019-01-10-speakers/" 
    - Schedule: "http://icra-2019-uwroboticsperception.ge.issia.cnr.it/2019-01-09-program/"
    - Presentations: "http://icra-2019-uwroboticsperception.ge.issia.cnr.it/2019-05-26-presentations/"
  Papers:
    - Authors Info: "http://icra-2019-uwroboticsperception.ge.issia.cnr.it/2019-01-06-papercall/"
    - Accepted Papers: "http://icra-2019-uwroboticsperception.ge.issia.cnr.it/2019-04-17-acceptedpapers/"
    - Best paper awards: "http://icra-2019-uwroboticsperception.ge.issia.cnr.it/2019-05-24-bestpapers/"
  Events/Jobs: "http://icra-2019-uwroboticsperception.ge.issia.cnr.it/2019-05-25-events/"
  Conclusions: "http://icra-2019-uwroboticsperception.ge.issia.cnr.it/2019-05-28-conclusions/"
  Organizers: "organizers"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/ws_logo/icra-ws-urp-logo.png"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
title-img: "/img/university-logos.png"

# --- Background colour/image options --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#E0E0EB"
navbar-text-col: "#000000"
navbar-children-col: "#F5F5F5"
page-col: "#FFFFFF"
link-col: "#800000"
hover-col: "#0085A1"
title-back-link-col: "#DDDDFF"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

#navbar-img: "/img/uw_bg_1.jpg"
# footer-img: "/img/bgimage.png"
# page-img: "/img/bgimage.png"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: MSc. Arturo Gomez Chavez -- Dr. Enrica Zereik

# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
# rss: false
  email: "a.gomezchavez@jacobs-university.de"
#  facebook: daattali
#  github: jacobs-robotics
#  twitter: arturokkboss33
#  reddit: yourname
#  google-plus: +DeanAttali
#  linkedin: https://www.linkedin.com/in/a-gomezchavez-smartrobots/
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  youtube: user/deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "IEEE-ICRA2019-UW-Perception.com"  # eg. "deanattali.com/beautiful-jekyll"

# --- Web Statistics Section --- #

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-134776668-1"

# Google Tag Manager ID
#gtm: ""

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.

#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# --- Misc --- #
# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: ""

# Facebook App ID
# fb_app_id: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Vancouver"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Use tags index page and make tags on each post clickable
link-tags: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
